[package]
name = "maka"
version = "0.1.0"
authors = ["morimolymoly <morimolymoly@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
uefi = "0.5.0"
